### ISSUE TITLE
ips running on daq modules nfq or afpacket ?

### ISSUE THREAD

**Issue by dipenpatel235** [royreinders/HomeIPS#2]
hello,,,
i am using raspberry pi and snort as ips.
in ips i am using daq with nfq but it is work as ids not work as ips.

so can u help me to fix issue ?

thanks

**Comment by royreinders** [comment]
Hi,

First off i'd like to note that this project is incomplete and no longer being worked on. However, to make sure snort actively blocks packets instead of just alerting make sure the rule 'action' is set to an option that drops or rejects the packet.
The following documentation will go in to more detail: http://manual-snort-org.s3-website-us-east-1.amazonaws.com/node29.html
